### ISSUE TITLE
/skin does not exist, and there is nothing about it in the config.yml.

### ISSUE THREAD

**Issue by Wertzui123** [poggit-orphanage/GrabBag#15]
/skin does not exist. What shoud In do?

**Comment by Awzaw** [comment]
From what I see it should be`/skin [player] [save|load|ls] [name]`, but I've no idea if it works. This plugin is such a mess it'll probably be archived from Poggit Orphanage soon.

**Comment by Wertzui123** [comment]
Ok, I found out that /skin is for older API. But some Features of the plugin are still working
