### ISSUE TITLE
Server thread/WARNING

### ISSUE THREAD

**Issue by BroCrows** [poggit-orphanage/GrabBag#17]
When I start my server all of the plugins are loading up nicely but this one, it says [Server thread/WARNING] Plugin ‘GrabBag’ has registered a listener for
‘pocketmine\event\server\RemoteServerCommandEvent’ on method ‘aliuly\grabbag\CmdSelMgr->onConsleCmd’, but the event Deprecated.

**Comment by dktapps** [comment]
duplicate of #12
