### ISSUE TITLE
Permissions

### ISSUE THREAD

**Issue by urhuckleberry51** [poggit-orphanage/GrabBag#18]
I want to give my admins gmc and i cant cause there is no permissions with the newest build

**Comment by Awzaw** [comment]
GrabBag is supposed to set permissions dynamically according to which features are enabled in the config. If you set `gm?: true` in the config, you should be able to give the permission gb.cmd.gmc to your Admins. That said, this plugin has so many problems that is no longer maintained, and will probably be removed from Poggit Orphanage soon.

**Comment by urhuckleberry51** [comment]
Thank you

**Comment by Awzaw** [comment]
Did that fix the issue?

**Comment by ghost** [comment]
I'm no longer active in the game. But I remember Grabbag was very practical and needed. (Google Translate)
