### ISSUE TITLE
(not an issue) how to remove /who /wild permission ?

### ISSUE THREAD

**Issue by teracube** [poggit-orphanage/GrabBag#6]
i want to remove /who command on my server with pureperms
on readme i don't find permissions nodes of who command
what are gb.cmd.  for these command ?

thanks

sorry for my bad english

**Comment by Awzaw** [comment]
I think /wild is EssentialsTP, so `essentialstp.command.wild`. And are you sure it's  `/who`? GrabBag only has `/whois` AFAIK, which is here: https://github.com/poggit-orphanage/GrabBag/blob/master/src/aliuly/grabbag/CmdWhois.php#L29

You can find all the permissions in the other command classes in that folder, but I think they are all `gb.cmd.<command>`

**Comment by teracube** [comment]
@Awzaw 
ok / who is an aliase of gb.cmd.players command

class CmdPlayers extends BasicCli implements CommandExecutor{
	public function __construct($owner){
		parent::__construct($owner);
		PermUtils::add($this->owner, "gb.cmd.players", "connected players", "true");
		$this->enableCmd("players",
			["description" => mc::_("show players connected and locations"),
				"usage" => mc::_("/players"),
				"aliases" => ["who"],
				"permission" => "gb.cmd.players"]);
	}
